name=Awattar
main=de.schnippsche.solarreader.plugins.awattar.Awattar
plugin.version=${project.version}
core.version=2.1
build=${maven.build.timestamp}
author=Stefan Toengi
repository=https://github.com/solarreader-plugins/plugin-awattar
icon=awattar.svg
supports=Awattar V1 API
interfaces=URL
protocol=HTTP
